### ISSUE TITLE
Lots of empty space

### ISSUE THREAD

**Issue by KeganMorin** [jordanralba/Portfolio#4]
I see a ton of space for information to be placed and if it is used it will make your website improve a whole bunch

**Comment by jamesrusso12** [comment]
nice

**Comment by jordanralba** [comment]
At the time of this issue's conception, the project was still in the design phase undergoing further development. The stated problem's proposed solution is to just complete finish developing the website and then its appearance will improve. As such, I will be closing the issue without plans to resolve it.
